name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.14"
      - name: Sync dependencies
        run: uv sync --all-extras
      - name: Run tests
        run: uv run pytest -v
